### ISSUE TITLE
Add dbgap attributes to Datasets

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#316]
```
      dbgap_sra_experiment_url:                                                                             
        type: string                                                                                        
        description: 'A URL linking the dataset to the associated uploaded data at dbGaP.'                  
      dbgap_study_url:                                                                                      
        type: string                                                                                        
        description: 'A URL linking the dataset to the particular study on dbGap it belongs to' 
```
