### ISSUE TITLE
Create new triggers to support hierarchy in the portal

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/entity-api#408]
Two new properties need to be added to the provenance schema.

For `Sample`:
```
organ_hierarchy:
  type: string
  description: 'The name of the top level of the hierarchy this organ belongs to based on its laterality.'
  on_index_trigger: get_organ_hierarchy
```

For `Dataset`:
```
dataset_type_hierarchy:
  type: string
  description: 'The name of the top level of the hierarchy this dataset type belongs to.'
  on_index_trigger: get_dataset_type_hierarchy
```
